### ISSUE TITLE
Remember project-related settings

### ISSUE THREAD

**Issue by markfodor** [thermoweb/jasypt-encrypt-plugin#7]
**Is your feature request related to a problem?**
No, it is a feature request.

**Describe the solution you'd like**
The plugin is extremely useful as it is, but it would be really neat if it could remember the previously used encryption algorithm in the project. So it would be automatically selected when the enryption/decryption popup is displayed.
As an extra, it would be nice if it would be able to recognized if the selected text is already wrapped in an "ENC(...)" block so users don`t need to tick that option on the popup.

**Describe alternatives you've considered**
-

**Additional context**
If someone uses the plugin frequently in many projects these little features could be very useful.

**Comment by thermoweb** [comment]
Hi, thanks for creating the issue. I'm glad you found the plugin useful :)

For the algorithm , the plugin should already remember what was used previously, and also for the "ENC(...)" checkbox since the #1 
Please check you have the last version of the plugin, if it's not working, try to see if the file `jasyptplugin.xml` exists in the .idea folder of your project. If not, maybe there is an issue :/

For the extra `recognized if the selected text is already wrapped in an "ENC(...)"` I will do it, because it's simple and seems right to check that.

Also I'm currently updating the plugin, so I'll ship this in the 1.2.x

**Comment by markfodor** [comment]
Thank you, that was superquick!
I have updated to the latest version and it does remember the algorithm. The jasyptplugin.xml has the saved value as well. Thanks!

I am wondering if it would be possible to remember the already used master password to a project. That way the plugin could check if the encrypted passwords are correct in each environment according to the provided jasypt master password. This could make the checking and testing a bit easier, especially when someone working with multiple projects/subprojects in the same repository. 
This is just an idea and I know it has a security-side as well which you need to consider.

**Comment by thermoweb** [comment]
I have a similar idea in mind.

I think the first version of that could be to remembrer the last used password and try to reuse it to decrypt. If it fail, the plugin will ask again.
For the encrypt part, it's not that simple since if the password is not the good one, the plugin could not know so I have to think about it.

But before doing that, I have to learn about the [CredentialAttributes](https://plugins.jetbrains.com/docs/intellij/persisting-sensitive-data.html) feature from jetbrains.

But feel free to open a new feature request :)

**Comment by markfodor** [comment]
Thank you! I have created an other feature request.
